### ISSUE TITLE
Adapter for c9/vfs

### ISSUE THREAD

**Issue by cadorn** [creationix/git-node-fs#6]
An adapter in the likes of https://github.com/creationix/git-node-fs/blob/master/lib/node-fs.js for https://github.com/c9/vfs

What would be involved?

**Comment by kriskowal** [comment]
Just need to create a package just like this one, perhaps `creationix/git-vfs`, that implements this interface: https://github.com/creationix/js-git/blob/master/doc/mixins/fs-db.md

**Comment by kriskowal** [comment]
Closing as out of scope for git-node-fs.
